exports.scalesArr = [
  {
    name: "Chromatic",
    intNotation: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    info: "The chromatic scale (or twelve-tone scale) is a set of twelve pitches (more completely, pitch classes) used in tonal music, with notes separated by the interval of a semitone. Almost all western musical instruments, such as the piano, are made to produce the chromatic scale, while other instruments capable of continuously variable pitch, such as the trombone and violin, can also produce microtones, or notes between those available on a piano. Most music uses subsets of the chromatic scale such as diatonic scales. While the chromatic scale is fundamental in western music theory, it is seldom directly used in its entirety in musical compositions or improvisation.",
    source: "factory",
  },
  {
    name: "Acoustic",
    intNotation: [0, 2, 4, 6, 7, 9, 10],
    info: "In music, the acoustic scale, overtone scale, Lydian dominant scale, Lydian ♭7 scale, or the Pontikonisian Scale is a seven-note synthetic scale.",
    source: "factory",
  },
  {
    name: "Aeolian (Natural Minor)",
    intNotation: [0, 2, 3, 5, 7, 8, 10],
    info: "The Aeolian mode is a musical mode or, in modern usage, a diatonic scale also called the natural minor scale. On the white piano keys, it is the scale that starts with A. Its ascending interval form consists of a key note, whole step, half step, whole step, whole step, half step, whole step, whole step. That means that, in A aeolian (or A minor), you would play A, move up a whole step (two piano keys) to B, move up a half step (one piano key) to C, then up a whole step to D, a whole step to E, a half step to F, a whole step to G, and a final whole step to a high A.",
    source: "factory",
  },
  {
    name: "Algerian",
    intNotation: [0, 2, 3, 6, 7, 9, 11, 12, 14, 15, 17],
    info: "The Algerian Scale is a scale frequently used in Algerian, Berber, and North African music. The frequent use of 1.5 steps in the scale contributes to a sound commonly associated with Moorish music.",
    source: "factory",
  },
  {
    name: "Altered (Super Locrian)",
    intNotation: [0, 1, 3, 4, 6, 8, 10],
    info: "In jazz, the altered scale, altered dominant scale, Palamidian Scale, or Super Locrian scale is a seven-note scale that is a dominant scale where all non-essential tones have been altered. This means that it comprises the three irreducibly essential tones that define a dominant seventh chord, which are root, major third, and minor seventh and that all other chord tones have been altered.",
    source: "factory",
  },
  {
    name: "Augmented",
    intNotation: [0, 3, 4, 7, 8, 11],
    info: "In music and music theory, a hexatonic scale is a scale with six pitches or notes per octave. Famous examples include the whole tone scale, C D E F♯ G♯ A♯ C; the augmented scale, C D♯ E G A♭ B C; the Prometheus scale, C D E F♯ A B♭ C; and the blues scale, C E♭ F G♭ G B♭ C. A hexatonic scale can also be formed by stacking perfect fifths. This results in a diatonic scale with one note removed (for example, A C D E F G).",
    source: "factory",
  },
  {
    name: "Bebop",
    intNotation: [0, 2, 4, 5, 7, 9, 10, 11],
    info: "Bebop scale is a term referring to common seven-note scales that have an added chromatic passing note. These are frequently used in jazz improvisation and are derived from the modes of the major scale, the melodic minor scale, and the harmonic minor scale. These scales are most often used by David Baker and Barry Harris as a tool to teach jazz improvisation. According to Corey Christiansen, \"David Baker, one of the world's finest jazz educators, named these scales the 'bebop scales' because they were used so often by jazz artists from the Bebop Era. These artists include Charlie Christian, Charlie Parker, Lester Young, and Dizzy Gillespie, to name a few.\"1] Barry Harris builds these scales from two unrelated 4-note chords, which gives them their names in his system.",
    source: "factory",
  },
  {
    name: "Blues",
    intNotation: [0, 3, 5, 6, 7, 10],
    info: 'The term blues scale refers to several different scales with differing numbers of pitches and related characteristics. A blues scale is often formed by the addition of an out-of-key "blue note" to an existing scale, notably the flat fifth addition to the minor pentatonic scale. However, the heptatonic blues scale can be considered a major scale with altered intervals.',
    source: "factory",
  },
  {
    name: "Dorian",
    intNotation: [0, 2, 3, 5, 7, 9, 10],
    info: "Dorian mode or Doric mode can refer to three very different but interrelated subjects: one of the Ancient Greek harmoniai (characteristic melodic behaviour, or the scale structure associated with it); one of the medieval musical modes; or—most commonly—one of the modern modal diatonic scales, corresponding to the piano keyboard's white notes from D to D, or any transposition of itself.",
    source: "factory",
  },
  {
    name: "Double harmonic",
    intNotation: [0, 1, 4, 5, 7, 8, 10],
    info: "In music, the double harmonic major scale is a scale whose gaps may sound unfamiliar to Western listeners. This is also known as Mayamalavagowla, Bhairav Raga, Byzantine scale, Arabic (Hijaz Kar), and Gypsy major. It can be likened to a gypsy scale because of the diminished step between the 1st and 2nd degrees. Arabic scale may also refer to any Arabic mode, the simplest of which, however, to Westerners, resembles the double harmonic major scale.",
    source: "factory",
  },
  {
    name: "Enigmatic",
    intNotation: [0, 1, 4, 6, 8, 10, 11],
    info: "The enigmatic scale is an unusual musical scale, with elements of both major and minor scales, as well as the whole-tone scale. It was originally published in a Milan journal as a musical challenge, with an invitation to harmonize it in some way.",
    source: "factory",
  },
  {
    name: "Flamenco",
    intNotation: [0, 1, 4, 5, 7, 8, 11],
    info: "In music theory, the flamenco mode (also Major-Phrygian) is a harmonized mode or scale abstracted from its use in flamenco music. In other words, it is the collection of pitches in ascending order accompanied by chords represents the pitches and chords used together in flamenco songs and pieces. The key signature is the same as that of the Phrygian mode (on E: no accidentals; on C: four flats), with the raised third and seventh being written in as necessary with accidentals. Its modal/tonal characteristics are prominent in the Andalusian cadence.",
    source: "factory",
  },
  {
    name: "Gypsy",
    intNotation: [0, 2, 3, 6, 7, 8, 10],
    info: 'The term Gypsy scale refers to one of several musical scales named after their support of and association with Romani or "Gypsy" music',
    source: "factory",
  },
  {
    name: "Half Diminished",
    intNotation: [0, 2, 3, 5, 6, 8, 10],
    info: "The half diminished scale or Sisyphean Scale is a seven-note musical scale. It is more commonly known as the Locrian ♮2 scale,[1] a name that avoids confusion with the diminished scale and the half-diminished seventh chord (minor seventh, diminished fifth). It is the sixth mode of the ascending form of the melodic minor scale (or jazz scale).",
    source: "factory",
  },
  {
    name: "Harmonic Major",
    intNotation: [0, 2, 4, 5, 7, 8, 11],
    info: "In music theory, the harmonic major scale is a musical scale found in some music from the common practice era and now used occasionally, most often in jazz. In George Russell's Lydian Chromatic Concept it is the fifth mode (V) of the Lydian Diminished scale.[1] It corresponds to the Raga Sarasangi in Indian Carnatic music.",
    source: "factory",
  },
  {
    name: "Harmonic Minor",
    intNotation: [0, 2, 3, 5, 7, 8, 11],
    info: "In music theory, the minor scale is three scale patterns – the natural minor scale, the harmonic minor scale, and the melodic minor scale – rather than just one as with the major scale.",
    source: "factory",
  },
  {
    name: "Hirajoshi",
    intNotation: [0, 4, 6, 7, 11],
    info: 'Hirajōshi scale, or hira-choshi (Japanese: 平調子, Hepburn: hirachōshi, chōshi = tuning and hira = even, level, tranquil, standard or regular) is a tuning scale adapted from shamisen music by Yatsuhashi Kengyō for tuning of the koto.[1] "The hirajoshi, kumoijoshi, and kokinjoshi "scales" are Western derivations of the koto tunings of the same names. These scales have been used by rock and jazz guitarists in search of "new" sounds.',
    source: "factory",
  },
  {
    name: "Hungarian Minor",
    intNotation: [0, 2, 3, 6, 7, 8, 11],
    info: "The Hungarian minor scale, double harmonic minor scale, or Gypsy minor scale is a type of combined musical scale. It is the fourth mode of the double harmonic scale. It is the same as the harmonic minor scale, except that it has a raised fourth scale degree to introduce an additional gap, or augmented second. It is a symmetrical scale with a slightly ambiguous tonal centre, due to the many half steps.",
    source: "factory",
  },
  {
    name: "In Scale",
    intNotation: [0, 1, 5, 7, 8],
    info: 'The Hungarian major scale is an ancohemitonic, heptatonic scale with the following interval structure in semitones: 3, 1, 2, 1, 2, 1, 2, giving it the notes C D♯ E F♯ G A B♭ in the key of C. As such the scale is a subset of the octatonic scale, alternating semitones and whole tones (on C: C D♭ E♭ F♭ G♭ G A B♭ C). It is, "used extensively in Hungarian gypsy music," as well as in classical music by composers including Franz Liszt (d. 1886) and Zoltán Kodály (d. 1967)," as well as in Thea Musgrave\'s Horn Concerto (1971).',
    source: "factory",
  },
  {
    name: "Insen",
    intNotation: [0, 1, 5, 7, 10],
    info: "Insen is a tuning scale adapted from shamisen music by Yatsuhashi Kengyō for tuning of the koto. It only differs from the hirajoshi scale by one note.",
    source: "factory",
  },
  {
    name: "Ionian (Major)",
    intNotation: [0, 2, 4, 5, 7, 9, 11],
    info: "The major scale is one of the most commonly used musical scales, especially in Western music. It is one of the diatonic scales. Like many musical scales, it is made up of seven notes: the eighth duplicates the first at double its frequency so that it is called a higher octave of the same note.",
    source: "factory",
  },
  {
    name: "Istrian",
    intNotation: [0, 1, 3, 4, 6, 7],
    info: '"Istrian scale" refers both to a "unique" musical scale of folk music genres from Istria and Kvarner which use the style. It is named for the Istrian peninsula. Istrian folk music is based on a distinctive six-tone musical scale (the so-called Istrian scale), and the peninsula\'s two-part, slightly nasal singing. The two-part singing and playing in the Istrian scale, a traditional singing practice characteristic of the Istrian region and the north Adriatic coastal area and islands, was inscribed in UNESCO\'s List of Intangible Cultural Heritage in 2009.',
    source: "factory",
  },
  {
    name: "Iwato",
    intNotation: [0, 1, 5, 6, 10],
    info: "The iwato scale is a musical scale that is similar to the Locrian mode, seventh mode of the major scale, different in that it has no 3rd or 6th notes, thus making it pentatonic. Its spelling is therefore 1 b2 4 b5 b7. It is used in traditional Japanese music for the koto. It is a mode of the Hirajōshi scale.",
    source: "factory",
  },
  {
    name: "Locrian",
    intNotation: [0, 1, 3, 5, 6, 8, 10],
    info: "The Locrian mode is either a musical mode or simply a diatonic scale. On the piano, it is the scale that starts with B and only uses the white keys from there. Its ascending form consists of the key note, a half step, two whole steps, a further half step, and three more whole steps.",
    source: "factory",
  },
  {
    name: "Lydian (augmented)",
    intNotation: [0, 2, 4, 6, 8, 9, 11],
    info: "In music, the Lydian augmented scale is the third mode of the ascending melodic minor scale or jazz minor scale.",
    source: "factory",
  },
  {
    name: "Lydian",
    intNotation: [0, 2, 4, 6, 7, 9, 11],
    info: "The modern Lydian mode is a seven-tone musical scale formed from a rising pattern of pitches comprising three whole tones, a semitone, two more whole tones, and a final semitone.",
    source: "factory",
  },
  {
    name: "Major Bebop",
    intNotation: [0, 2, 4, 5, 7, 8, 9, 11],
    info: "Bebop scale is a term referring to common seven-note scales that have an added chromatic passing note. These are frequently used in jazz improvisation and are derived from the modes of the major scale, the melodic minor scale, and the harmonic minor scale.",
    source: "factory",
  },
  {
    name: "Major Locrian",
    intNotation: [0, 2, 4, 5, 6, 8, 10],
    info: "In music, the major Locrian scale, also called the Locrian major scale, is the scale obtained by sharpening the second and third notes of the diatonic Locrian mode. With a tonic of C, it consists of the notes C D E F G♭ A♭ B♭. It can be described as a whole tone scale extending from G♭ to E, with F introduced within the diminished third interval from E to G♭. The scale therefore shares with the Locrian mode the property of having a diminished fifth above the tonic.",
    source: "factory",
  },
  {
    name: "Major Pentatonic",
    intNotation: [0, 2, 4, 7, 9],
    info: "A pentatonic scale is a musical scale with five notes per octave, in contrast to the heptatonic scale, which has seven notes per octave.",
    source: "factory",
  },
  {
    name: "Melodic Minor (ascending)",
    intNotation: [0, 2, 3, 5, 7, 9, 11],
    info: "In music theory, the minor scale is three scale patterns – the natural minor scale, the harmonic minor scale, and the melodic minor scale – rather than just two as with the major scale, which also has a harmonic form but lacks a melodic form.",
    source: "factory",
  },
  {
    name: "Minor Pentatonic",
    intNotation: [0, 3, 5, 7, 10],
    info: "A pentatonic scale is a musical scale with five notes per octave, in contrast to the heptatonic scale, which has seven notes per octave.",
    source: "factory",
  },
  {
    name: "Mixolydian",
    intNotation: [0, 2, 4, 5, 7, 9, 10],
    info: "Mixolydian mode may refer to one of three things: the name applied to one of the ancient Greek harmoniai or tonoi, based on a particular octave species or scale; one of the medieval church modes; or a modern musical mode or diatonic scale, related to the medieval mode.",
    source: "factory",
  },
  {
    name: "Neapolitan Major",
    intNotation: [0, 1, 3, 5, 7, 9, 11],
    info: "In music, the major Neapolitan scale and the minor Neapolitan scale are two musical scales. Both scales are minor, despite their names.",
    source: "factory",
  },
  {
    name: "Neapolitan Minor",
    intNotation: [0, 1, 3, 5, 7, 8, 11],
    info: "In music, the major Neapolitan scale and the minor Neapolitan scale are two musical scales. Both scales are minor, despite their names.",
    source: "factory",
  },
  {
    name: "Octatonic 1",
    intNotation: [0, 2, 3, 5, 6, 8, 9, 11],
    info: "An octatonic scale is any eight-note musical scale. However, the term most often refers to the symmetric scale composed of alternating whole and half steps, as shown at right. In classical theory, this scale is commonly called the octatonic scale, although there are a total of 42 enharmonically non-equivalent, transpositionally non-equivalent eight-note sets.",
    source: "factory",
  },
  {
    name: "Octatonic 2",
    intNotation: [0, 1, 3, 4, 6, 7, 9, 10],
    info: "An octatonic scale is any eight-note musical scale. However, the term most often refers to the symmetric scale composed of alternating whole and half steps, as shown at right. In classical theory, this scale is commonly called the octatonic scale, although there are a total of 42 enharmonically non-equivalent, transpositionally non-equivalent eight-note sets.",
    source: "factory",
  },
  {
    name: "Persian",
    intNotation: [0, 1, 4, 5, 6, 8, 11],
    info: "The Persian scale is a musical scale occasionally found in guitar scale books, along with other scales inspired by Middle Eastern music. It is characterized by the liberal use of half steps (4), augmented seconds (2), and frequent use of chromaticism. Compare this to the one augmented second of the harmonic minor or the use of only two half-steps in all diatonic scales. This is also the Locrian mode with a major third and major seventh degree.",
    source: "factory",
  },
  {
    name: "Phrygian (Dominant)",
    intNotation: [0, 1, 4, 5, 7, 8, 10],
    info: 'In music, the Phrygian dominant scale is the fifth mode of the harmonic minor scale, the fifth being the dominant. Also called the altered Phrygian scale, dominant flat 2 flat 6 (in jazz), the Freygish scale (also spelled Fraigish), harmonic dominant, or simply the fifth mode of the harmonic minor scale. It resembles the scale of the Phrygian mode but has a major third. In the Berklee method, it is known as the Mixolydian ♭9 ♭13 chord scale, a Mixolydian scale with a lowered 9th (2nd) and lowered 13th (6th), used in secondary dominant chord scales for V7/III and V7/VI. Bebop jazz pianist Barry Harris added a note to the scale and describes his use as "on C7, play down from the 7th of Eb7 to E the 3rd of C7” and especially over G-7b5 to C7b9 (the ii V in minor). He nicknamed this eight tone scale “the minor’s five”. Being eight tones it has the advantage of placing the chord tones on the beats which enables a melody to reinforce the underlying harmony. It also eliminates the harsh augmented 2nd melodic interval found in the seven tone 5th mode of harmonic minor scale. Another advantage is that gives improvisers an access to their often more familiar dominant scale vocabulary. Barry Harris further recognized that its descending form has an especially melodic quality rather than being played up from a root. He said he noticed this particular descending permutation being played by Charlie Parker several times on “What Is This Thing Called Love?”.',
    source: "factory",
  },
  {
    name: "Phrygian",
    intNotation: [0, 1, 3, 5, 7, 8, 10],
    info: "The Phrygian mode can refer to three different musical modes: the ancient Greek tonos or harmonia sometimes called Phrygian, formed on a particular set of octave species or scales; the Medieval Phrygian mode, and the modern conception of the Phrygian mode as a diatonic scale, based on the latter.",
    source: "factory",
  },
  {
    name: "Prometheus",
    intNotation: [0, 2, 4, 6, 9, 10],
    info: "In music, the mystic chord or Prometheus chord is a six-note synthetic chord and its associated scale, or pitch collection; which loosely serves as the harmonic and melodic basis for some of the later pieces by Russian composer Alexander Scriabin. Scriabin, however, did not use the chord directly but rather derived material from its transpositions.",
    source: "factory",
  },
  {
    name: "Scale of Harmonics",
    intNotation: [0, 3, 4, 5, 7, 9],
    info: "The scale of harmonics is a musical scale based on the noded positions of the natural harmonics existing on a string. This musical scale is present on the guqin, regarded as one of the first string instruments with a musical scale. Most fret positions appearing on Non-Western string instruments (lutes) are equal to positions of this scale. Unexpectedly, these fret positions are actually the corresponding undertones of the overtones from the harmonic series. The distance from the nut to the fret is an integer number lower than the distance from the fret to the bridge.",
    source: "factory",
  },
  {
    name: "Tritone",
    intNotation: [0, 1, 4, 6, 7, 10],
    info: "In music and music theory, a hexatonic scale is a scale with six pitches or notes per octave. Famous examples include the whole tone scale, C D E F♯ G♯ A♯ C; the augmented scale, C D♯ E G A♭ B C; the Prometheus scale, C D E F♯ A B♭ C; and the blues scale, C E♭ F G♭ G B♭ C. A hexatonic scale can also be formed by stacking perfect fifths. This results in a diatonic scale with one note removed.",
    source: "factory",
  },
  {
    name: "Two Semitone Tritone",
    intNotation: [0, 1, 2, 6, 7, 8],
    info: "In music and music theory, a hexatonic scale is a scale with six pitches or notes per octave. Famous examples include the whole tone scale, C D E F♯ G♯ A♯ C; the augmented scale, C D♯ E G A♭ B C; the Prometheus scale, C D E F♯ A B♭ C; and the blues scale, C E♭ F G♭ G B♭ C. A hexatonic scale can also be formed by stacking perfect fifths. This results in a diatonic scale with one note removed.",
    source: "factory",
  },
  {
    name: "Ukrainian Dorian",
    intNotation: [0, 2, 3, 6, 7, 9, 10],
    info: 'In music, the Romanian Minor scale or Ukrainian Dorian scale or altered Dorian scale is a musical scale or the fourth mode of the harmonic minor scale. It is "similar to the dorian mode, but with a tritone and variable sixth and seventh degrees". It is related to both the Freygish and Misheberak scales and is used in Jewish music, "predominant in klezmer bulgarish and doina (doyne)." "When the Ukrainian Dorian scale functions in the synagogue, it is a mode known as the Mi sheberach or Av horachamon. Arab and Greek scholars give other names to the scale: Nikriz (نكريز) and Aulos, respectively."',
    source: "factory",
  },
  {
    name: "Whole Tone",
    intNotation: [0, 2, 4, 6, 8, 10],
    info: "In music, a whole-tone scale is a scale in which each note is separated from its neighbors by the interval of a whole tone. In twelve-tone equal temperament, there are only two complementary whole-tone scales, both six-note or hexatonic scales. A single whole-tone scale can also be thought of as a 'six-tone equal temperament'.",
    source: "factory",
  },
  {
    name: "Yo",
    intNotation: [0, 3, 5, 7, 10],
    info: "The yo scale, which does not contain minor notes, according to a traditional theory is a pentatonic scale used in much Japanese music including gagaku and shomyo. The yo scale is used specifically in folk songs and early popular songs and is contrasted with the in scale which does contain minor notes. The in scale is described as 'dark' while the yo scale is described as 'bright' sounding.",
    source: "factory",
  },
];

